"use client";

import { useEffect, useState } from "react";

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const projects = [
  { tag: "Agricultura familiar", title: "Da Terra à Mesa", text: "Fortalecimento de famílias agricultoras, produção sustentável e acesso a mercados locais.", image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1200&q=85" },
  { tag: "Capacitação", title: "Capacita Campo", text: "Formação prática em gestão, produção agroecológica e comercialização para quem vive da terra.", image: "https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1200&q=85" },
  { tag: "Comunidade", title: "Hortas que Aproximam", text: "Cultivo coletivo, alimentação saudável e geração de renda em espaços urbanos e rurais.", image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1200&q=85" },
  { tag: "Inclusão produtiva", title: "Criando Oportunidades", text: "Capacitação, orientação e caminhos para ampliar renda, autonomia e oportunidades nas comunidades.", image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85" },
  { tag: "Segurança alimentar", title: "Ceará sem Fome", text: "Ações de mobilização e apoio voltadas ao acesso à alimentação e ao fortalecimento das famílias cearenses.", image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=85" },
];

const editorialPosts = [
  { category: "Agricultura familiar", date: "18 jun 2026", title: "Produção local fortalece famílias e movimenta municípios", text: "Iniciativas de assistência técnica e acesso a mercados ampliam a autonomia de quem vive da terra.", image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1200&q=85" },
  { category: "Capacitação", date: "10 jun 2026", title: "Conhecimento compartilhado vira oportunidade no campo", text: "Formações práticas conectam gestão, produção sustentável e novos caminhos para geração de renda.", image: "https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1200&q=85" },
  { category: "Segurança alimentar", date: "28 mai 2026", title: "Ceará sem Fome: mobilização que chega a quem precisa", text: "Parcerias e atuação territorial ajudam a promover dignidade e acesso à alimentação de qualidade.", image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=85" },
  { category: "Histórias de impacto", date: "16 mai 2026", title: "Criando Oportunidades aproxima formação e autonomia", text: "Pessoas, saberes e redes locais se encontram para construir novas perspectivas de futuro.", image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85" },
  { category: "Sustentabilidade", date: "04 mai 2026", title: "Cuidar do solo é cultivar o futuro dos municípios", text: "Práticas responsáveis protegem recursos naturais e tornam a produção familiar mais resiliente.", image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=1200&q=85" },
  { category: "Institucional", date: "22 abr 2026", title: "Transparência e diálogo para transformar juntos", text: "O Instituto reforça seu compromisso com informação acessível, participação e resultados mensuráveis.", image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1200&q=85" },
];

function moveCarousel(id: string, direction: number) {
  document.getElementById(id)?.scrollBy({ left: direction * 420, behavior: "smooth" });
}

function getInstagramPosts() {
  return [
    { id: "demo-1", image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=900&q=85", date: "2 dias", caption: "Dia de campo com famílias agricultoras: troca de saberes, cuidado com o solo e novas possibilidades para a produção local.", likes: 184 },
    { id: "demo-2", image: "https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=900&q=85", date: "5 dias", caption: "Mais uma turma do Capacita Campo concluída. Conhecimento compartilhado é oportunidade que permanece no território.", likes: 231 },
    { id: "demo-3", image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=900&q=85", date: "1 semana", caption: "Mobilização, alimento e cuidado: seguimos juntos fortalecendo ações de segurança alimentar no Ceará.", likes: 297 },
    { id: "demo-4", image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=900&q=85", date: "2 semanas", caption: "Quando a comunidade cultiva junto, crescem vínculos, renda, autonomia e esperança.", likes: 156 },
  ];
}

function InstagramFeed({ variant }: { variant: "minimal" | "wild" }) {
  const posts = getInstagramPosts();
  return <section className={`instagram-feed instagram-${variant}`} id={variant === "minimal" ? "instagram" : "wild-instagram"}>
    <div className="instagram-heading"><div><span className="demo-label">Demonstração · conteúdo fictício</span><p>ACOMPANHE NO INSTAGRAM</p><h2>@sementesdasustentabilidade</h2></div><a href="#" aria-label="Abrir perfil demonstrativo no Instagram">Seguir perfil <span>↗</span></a></div>
    <div className="instagram-grid">{posts.map((post) => <article className="instagram-card" key={post.id}><div className="instagram-image"><img src={post.image} alt="Publicação demonstrativa sobre ações do Instituto" /><span aria-hidden="true">◎</span></div><div className="instagram-meta"><span>♥ {post.likes}</span><span>{post.date}</span></div><p><strong>@sementesdasustentabilidade</strong> {post.caption}</p></article>)}</div>
  </section>;
}

function Mark({ light = false, goHome }: { light?: boolean; goHome?: () => void }) {
  return <a href="#inicio" onClick={goHome ? (event) => { event.preventDefault(); goHome(); } : undefined} className={`mark ${light ? "mark-light" : ""}`} aria-label="Instituto Sementes da Sustentabilidade — início"><img className="brand-logo" src={`${basePath}/logo-iss-raster.png`} alt="Instituto Sementes da Sustentabilidade" /></a>;
}

function Minimal({ openPosts }: { openPosts: () => void }) {
  return <main className="minimal" id="inicio">
    <header className="min-header"><Mark /><nav aria-label="Navegação principal"><a href="#sobre">O Instituto</a><a href="#projetos">Projetos</a><a href="#posts" onClick={(event) => { event.preventDefault(); openPosts(); }}>Posts</a><a href="#transparencia">Transparência</a><a href="#contato">Contato</a></nav><a className="min-contact" href="#contato">Fale conosco <span>↗</span></a></header>
    <section className="min-hero">
      <div className="min-hero-copy"><p className="eyebrow">Impacto social · agricultura familiar · sustentabilidade</p><h1>Cultivamos futuros que florescem juntos.</h1><p className="lead">Fortalecemos pessoas e territórios por meio da agricultura familiar, da educação e da ação comunitária.</p><a className="button button-green" href="#projetos">Conheça nossos projetos <span>↗</span></a></div>
      <figure className="min-hero-image"><img src="https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1600&q=90" alt="Agricultor familiar caminhando em uma plantação" /><figcaption><span>01</span> Conhecimento e terra cultivam autonomia.</figcaption></figure>
    </section>
    <section className="min-intro" id="sobre"><p className="section-index">01 — Quem somos</p><div><h2>Transformação que nasce da terra e cresce em comunidade.</h2><p>O Instituto acredita na agricultura familiar como força de desenvolvimento local. Conectamos conhecimento, cuidado e oportunidades para valorizar quem produz, proteger o território e fazer esse potencial crescer.</p><a className="text-link" href="#">Conheça nossa história <span>→</span></a></div></section>
    <section className="min-pillars" aria-label="Eixos de atuação"><article><span>01</span><h3>Agricultura familiar</h3><p>Assistência, fortalecimento produtivo e acesso a mercados para famílias do campo.</p></article><article><span>02</span><h3>Capacitação</h3><p>Conhecimento prático para ampliar autonomia, renda e protagonismo comunitário.</p></article><article><span>03</span><h3>Sustentabilidade</h3><p>Produção responsável que protege o solo, a água e as próximas gerações.</p></article></section>
    <section className="min-stats" aria-label="Indicadores de impacto"><div><strong>320</strong><span>famílias agricultoras<br />acompanhadas</span></div><div><strong>680</strong><span>pessoas<br />capacitadas</span></div><div><strong>12</strong><span>comunidades<br />fortalecidas</span></div><div><strong>86%</strong><span>dos recursos na<br />atividade-fim</span></div></section>
    <section className="min-projects" id="projetos"><div className="section-heading"><div><p className="section-index">02 — Nossa atuação</p><h2>Projetos que deixam raízes.</h2></div><div className="carousel-actions"><span>Explore os projetos</span><button type="button" onClick={() => moveCarousel("min-project-carousel", -1)} aria-label="Projetos anteriores">←</button><button type="button" onClick={() => moveCarousel("min-project-carousel", 1)} aria-label="Próximos projetos">→</button></div></div><div className="project-grid" id="min-project-carousel" role="region" aria-label="Carrossel de projetos" tabIndex={0}>{projects.map((p, i) => <article className="min-card" key={p.title}><a href="#"><div className="card-image"><img src={p.image} alt="" /><span>0{i + 1}</span></div><p className="eyebrow">{p.tag}</p><h3>{p.title}</h3><p>{p.text}</p><span className="circle-arrow">↗</span></a></article>)}</div></section>
    <section className="min-news" id="noticias"><div><p className="section-index">03 — Histórias e notícias</p><h2>O que estamos<br />cultivando agora.</h2><a className="text-link" href="#posts" onClick={(event) => { event.preventDefault(); openPosts(); }}>Ver todos os posts <span>→</span></a></div><article><img src="https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=1400&q=85" alt="Grupo de voluntários sorrindo" /><div><p className="eyebrow">Histórias de impacto · 12 jun 2026</p><h3>Quando uma horta vira ponto de encontro, renda e esperança</h3><p>Conheça as pessoas que estão transformando um terreno ocioso em alimento, autonomia e convivência.</p><a className="text-link" href="#posts" onClick={(event) => { event.preventDefault(); openPosts(); }}>Ler história <span>→</span></a></div></article></section>
    <InstagramFeed variant="minimal" />
    <section className="min-transparency" id="transparencia"><div><p className="section-index">04 — Transparência</p><h2>Confiança também se cultiva.</h2></div><div><p>Resultados, documentos e informações acessíveis para quem acredita e caminha ao nosso lado.</p><a className="button button-outline" href="#">Acessar portal da transparência <span>↗</span></a></div></section>
    <footer className="min-footer" id="contato"><div className="footer-main"><Mark light /><div><p className="eyebrow">Vamos conversar</p><a className="mail" href="mailto:contato@sementesdasustentabilidade.org.br">contato@sementesdasustentabilidade.org.br</a></div></div><div className="footer-bottom"><span>© 2026 Instituto Sementes da Sustentabilidade</span><div><a href="#">Instagram</a><a href="#">LinkedIn</a><a href="#">Política de privacidade</a></div></div></footer>
  </main>;
}

function Wild({ openPosts }: { openPosts: () => void }) {
  return <main className="wild" id="inicio-wild">
    <header className="wild-header"><Mark light /><nav aria-label="Navegação principal"><a href="#manifesto">Instituto</a><a href="#wild-projects">Projetos</a><a href="#posts" onClick={(event) => { event.preventDefault(); openPosts(); }}>Posts</a><a href="#wild-transparency">Transparência</a></nav><a className="wild-pill" href="#wild-contact">Vamos conversar ↗</a></header>
    <section className="wild-hero">
      <div className="orb orb-one"/><div className="orb orb-two"/><span className="vertical-note">DESDE 2019 · BRASIL</span>
      <p className="wild-kicker">Agricultura familiar · impacto social que cria raízes</p><h1>Semeamos <em>hoje</em><br />as comunidades<br /><span>sustentáveis</span> de amanhã.</h1>
      <div className="wild-hero-photo"><img src="https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1400&q=90" alt="Agricultor familiar em uma área de cultivo" /><span className="photo-sticker">saber que<br />floresce ✦</span></div>
      <a className="wild-cta" href="#wild-projects">Conheça nossos projetos <b>↘</b></a><p className="wild-side-copy">Agricultura familiar, educação e ação comunitária para transformar pessoas e territórios.</p><span className="family-seal">AGRICULTURA<br /><b>FAMILIAR</b><br />✦</span>
    </section>
    <section className="wild-manifesto" id="manifesto"><div className="marquee"><span>GENTE ✦ TERRA ✦ AGRICULTURA FAMILIAR ✦ FUTURO ✦ GENTE ✦ TERRA ✦</span></div><div className="manifesto-grid"><p>(NOSSO JEITO DE FAZER)</p><h2>Valorizamos quem vive da terra.<br /><i>Plantamos caminhos</i>, escutamos famílias agricultoras e construímos junto.</h2><div className="manifesto-seal">ISS<br /><span>✦</span><br />2026</div></div></section>
    <section className="wild-projects" id="wild-projects"><div className="wild-title"><p>PROJETOS / 2026</p><h2>Onde nossas<br />sementes <i>viram</i><br /><span>movimento.</span></h2><div className="wild-carousel-actions"><button type="button" onClick={() => moveCarousel("wild-project-carousel", -1)} aria-label="Projetos anteriores">←</button><button type="button" onClick={() => moveCarousel("wild-project-carousel", 1)} aria-label="Próximos projetos">→</button></div></div><div className="wild-cards" id="wild-project-carousel" role="region" aria-label="Carrossel de projetos" tabIndex={0}>{projects.map((p, i) => <article className={`wild-card wild-card-${i + 1}`} key={p.title}><img src={p.image} alt="" /><div><span>0{i + 1} / {p.tag}</span><h3>{p.title}</h3><p>{p.text}</p><a href="#">descobrir projeto ↗</a></div></article>)}</div></section>
    <section className="wild-impact"><div className="impact-intro"><p>IMPACTO EM MOVIMENTO</p><h2>Conhecimento no campo.<br />Autonomia que fica <i>viva.</i></h2></div><div className="impact-numbers"><div><strong>320</strong><p>famílias agricultoras<br />acompanhadas</p></div><div><strong>680</strong><p>pessoas<br />capacitadas</p></div><div><strong>12</strong><p>comunidades<br />fortalecidas</p></div></div></section>
    <section className="wild-news" id="wild-news"><div className="news-photo"><img src="https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1400&q=85" alt="Mãos segurando uma jovem planta"/><span>LER EM 4 MIN ↗</span></div><div className="news-copy"><p>DIÁRIO DE CAMPO · 12.06.26</p><h2>Uma semente,<br />muitas mãos<br />e um município<br /><i>inteiro.</i></h2><p>Como a agricultura familiar e a capacitação fortalecem o território, gerando alimento, renda e desenvolvimento local.</p><a href="#posts" onClick={(event) => { event.preventDefault(); openPosts(); }}>LER ESSA HISTÓRIA <span>→</span></a></div><div className="sun-shape">✦</div></section>
    <InstagramFeed variant="wild" />
    <section className="wild-transparency" id="wild-transparency"><div><span>TRANSPARÊNCIA</span><h2>Tudo aberto.<br />Tudo às claras.</h2></div><p>Porque confiança não é discurso — é prática. Acompanhe nossos resultados, documentos e a aplicação de cada recurso.</p><a href="#">ABRIR PORTAL <b>↗</b></a></section>
    <footer className="wild-footer" id="wild-contact"><div className="footer-burst">VAMOS<br /><i>cultivar</i><br />JUNTOS?</div><a className="wild-email" href="mailto:contato@sementesdasustentabilidade.org.br">contato@sementesdasustentabilidade.org.br ↗</a><div className="wild-footer-bottom"><Mark light/><div><a href="#">Instagram ↗</a><a href="#">LinkedIn ↗</a></div><span>BRASIL · 2026</span></div></footer>
  </main>;
}

function MinimalPosts({ goHome }: { goHome: () => void }) {
  return <main className="minimal posts-minimal" id="posts"><header className="min-header posts-header"><Mark goHome={goHome} /><nav aria-label="Navegação de posts"><button onClick={goHome}>Home</button><a href="#arquivo">Notícias</a><a href="#arquivo">Histórias</a><a href="#arquivo">Artigos</a></nav><a className="min-contact" href="mailto:contato@sementesdasustentabilidade.org.br">Fale conosco <span>↗</span></a></header><section className="posts-min-hero"><span className="demo-label">Página demonstrativa</span><p className="section-index">Comunicação institucional</p><h1>Informação que<br />cultiva confiança.</h1><p>Notícias, histórias e conhecimento para aproximar pessoas, compartilhar resultados e dar voz a quem transforma os municípios.</p></section><section className="posts-min-feature"><img src={editorialPosts[0].image} alt="Agricultora trabalhando em produção familiar" /><div><p className="eyebrow">{editorialPosts[0].category} · {editorialPosts[0].date}</p><h2>{editorialPosts[0].title}</h2><p>{editorialPosts[0].text}</p><a href="#" className="text-link">Ler publicação <span>→</span></a></div></section><section className="posts-min-archive" id="arquivo"><div className="posts-archive-head"><div><p className="section-index">Publicações recentes</p><h2>Do Instituto<br />para você.</h2></div><div className="post-filters" aria-label="Categorias"><button className="active">Todos</button><button>Projetos</button><button>Notícias</button><button>Histórias</button></div></div><div className="posts-min-grid">{editorialPosts.slice(1).map((post) => <article key={post.title}><img src={post.image} alt="" /><p className="eyebrow">{post.category} · {post.date}</p><h3>{post.title}</h3><p>{post.text}</p><a href="#" aria-label={`Ler ${post.title}`}>Ler mais ↗</a></article>)}</div></section><section className="posts-newsletter"><div><p className="section-index">Boletim Sementes</p><h2>Receba nossas novidades.</h2></div><form onSubmit={(event) => event.preventDefault()}><label htmlFor="min-email">Seu melhor e-mail</label><div><input id="min-email" type="email" placeholder="voce@exemplo.com" /><button type="submit">Quero receber →</button></div></form></section><footer className="min-footer"><div className="footer-main"><Mark light goHome={goHome} /><div><p className="eyebrow">Comunicação também é transparência</p><button className="back-home" onClick={goHome}>← Voltar para a Home</button></div></div></footer></main>;
}

function WildPosts({ goHome }: { goHome: () => void }) {
  return <main className="wild posts-wild" id="posts"><header className="wild-header posts-header"><Mark light goHome={goHome} /><nav aria-label="Navegação de posts"><button onClick={goHome}>Home</button><a href="#wild-archive">Notícias</a><a href="#wild-archive">Histórias</a><a href="#wild-archive">Artigos</a></nav><a className="wild-pill" href="mailto:contato@sementesdasustentabilidade.org.br">Vamos conversar ↗</a></header><section className="posts-wild-hero"><span className="demo-label">PÁGINA DEMO ✦ COMUNICAÇÃO INSTITUCIONAL</span><p>VOZES DO TERRITÓRIO · IDEIAS QUE CIRCULAM</p><h1>Notícia boa<br /><i>cria raízes.</i></h1><div className="posts-wild-stamp">LER<br />COMPARTILHAR<br />TRANSFORMAR ✦</div></section><section className="posts-wild-feature"><div className="wild-feature-image"><img src={editorialPosts[0].image} alt="Agricultura familiar em campo" /><span>DESTAQUE / 01</span></div><div><p>{editorialPosts[0].category} · {editorialPosts[0].date}</p><h2>Produção local<br /><i>movimenta</i><br />municípios.</h2><p>{editorialPosts[0].text}</p><a href="#">LER AGORA <span>↗</span></a></div></section><section className="posts-wild-archive" id="wild-archive"><div className="wild-archive-title"><p>ÚLTIMAS PUBLICAÇÕES / 2026</p><h2>Leia.<br /><i>Descubra.</i><br />Compartilhe.</h2></div><div className="posts-wild-grid">{editorialPosts.slice(1).map((post, index) => <article key={post.title}><span>0{index + 2} / {post.category}</span><img src={post.image} alt="" /><h3>{post.title}</h3><p>{post.text}</p><a href="#">ABRIR HISTÓRIA ↗</a></article>)}</div></section><section className="posts-wild-newsletter"><p>BOLETIM SEMENTES</p><h2>A novidade<br />chega <i>primeiro</i><br />por aqui.</h2><form onSubmit={(event) => event.preventDefault()}><input aria-label="Seu e-mail" type="email" placeholder="SEU E-MAIL" /><button type="submit">QUERO RECEBER ↗</button></form></section><footer className="wild-footer"><div className="footer-burst">NOSSA VOZ<br /><i>também</i><br />TRANSFORMA.</div><button className="back-home wild-back" onClick={goHome}>← VOLTAR PARA A HOME</button></footer></main>;
}

export default function Home() {
  const [design, setDesign] = useState<"minimal" | "wild">("minimal");
  const [page, setPage] = useState<"home" | "posts">("home");
  useEffect(() => { window.scrollTo({ top: 0, behavior: "smooth" }); }, [design, page]);
  const openPosts = () => setPage("posts");
  const goHome = () => setPage("home");
  return <><div className="design-switcher" role="group" aria-label="Alternar proposta visual"><span>{page === "home" ? "Escolha o design" : "Posts · escolha o design"}</span><button onClick={() => setDesign("minimal")} className={design === "minimal" ? "active" : ""} aria-pressed={design === "minimal"}>01 Minimalista</button><button onClick={() => setDesign("wild")} className={design === "wild" ? "active" : ""} aria-pressed={design === "wild"}>02 Extravagante</button></div>{page === "home" ? (design === "minimal" ? <Minimal openPosts={openPosts} /> : <Wild openPosts={openPosts} />) : (design === "minimal" ? <MinimalPosts goHome={goHome} /> : <WildPosts goHome={goHome} />)}</>;
}
